version: 2
updates:
- package-ecosystem: bundler
  directory: "rails-auth-server/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "rails-auth-server/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
